//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUEST_ACCESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class preguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public preguntas()
        {
            this.respuestas = new HashSet<respuestas>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string tipoPregunta { get; set; }
        public int idCuestionario { get; set; }
    
        public virtual cuestionarios cuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestas> respuestas { get; set; }
    }
}
